In [1]:
import torch
import numpy as np

from trainer import load_embeddings
from lib.tokenizer import preprocessor
from lib.config import MODEL_EC, DEVICE
from lib.data_utils import vectorize

Running on: cuda
Reading twitter_2018 - 1grams ...
/home/houyu/.ekphrasis/stats/twitter_2018/counts_1grams.txt
Reading twitter_2018 - 2grams ...
/home/houyu/.ekphrasis/stats/twitter_2018/counts_2grams.txt
Reading twitter_2018 - 1grams ...
/home/houyu/.ekphrasis/stats/twitter_2018/counts_1grams.txt


In [11]:
def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

In [27]:
labels = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust', 'neutral']
model_path = '/home/houyu/learning/FinalProject/out/model/EmotionClassification_0.5900_2019-05-06_00:51.model'
model_conf = MODEL_EC
max_length = 65  # 85 train 65 dev 58 test
dev_path = '/home/houyu/learning/FinalProject/datasets/new/E-c-En-dev.txt'

# Loading model
model = torch.load(model_path)
model.eval()
word2idx, _, embeddings = load_embeddings(model_conf)

head = 1
cnt = 0
with open(dev_path, 'r') as fin:
    for line in fin.readlines():
        if head == 1:
            head = 0
            continue
        
        items = line[:len(line)-1].split('\t')
        
        input_text = items[1]

        # Pre-processing inputs
        pro_sent = preprocessor(input_text)

        # Embedding and vectorize
        sample = vectorize(pro_sent, word2idx, max_length)

        # Processing to get model inputs
        samples = []
        lengths = []
        samples.append(sample)
        lengths.append(len(pro_sent))

        samples = np.asarray(samples)
        lengths = np.asarray(lengths)

        samples = torch.tensor(samples)
        lengths = torch.tensor(lengths)

        samples = samples.to(DEVICE)
        lengths = lengths.to(DEVICE)


        # Running model
        outputs, attentions = model(samples, lengths)

        posts = outputs.data.cpu().numpy()
        # predicted = np.clip(np.sign(posts), a_min=0, a_max=None)    # 1   1   0   0   0   0   1   0   0   0   1
        # predicted = predicted.astype(np.int32)
        
        pro_sigmoid = sigmoid(posts)
        predicted = np.clip(np.sign(pro_sigmoid - 0.5), a_min=0, a_max=None)
        predicted = predicted.astype(np.int32)
        
        gold_labels = []
        for item in items[2:13]:
            gold_labels.append(int(item))
        
        gold_labels = np.asarray(gold_labels)
        
        acc = 0
        and_ = (predicted & gold_labels).sum()
        or_ = (predicted | gold_labels).sum()
        if(or_ != 0):
            acc = and_/or_
        
        # print(predicted)
        # print(gold_labels)
        # print(acc)
        
        # pro_sigmoid = sigmoid(posts)
        
        # break
        if acc >= 0.98:            # <= 0.5 错误分析
            print(input_text)
            print(pro_sent)
            print(attentions)
            print(posts)
            print(pro_sigmoid)
            print(gold_labels)
            cnt += 1

cnt

Loading word embeddings: ntua_twitter_affect_310 ...
Loaded word embeddings from cache.
@RanaAyyub @rajnathsingh Oh, hidden revenge and anger...I rememberthe time,she rebutted you.
['<user>', '<user>', 'oh', ',', 'hidden', 'revenge', 'and', 'anger', '.', '<repeated>', 'i', 'rememberthe', 'time', ',', 'she', 'rebutted', 'you', '.']
tensor([0.0555, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556,
        0.0556, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556, 0.0556],
       device='cuda:0', grad_fn=<DivBackward1>)
[ 5.34075308 -3.53363538  0.70751953 -4.59115553 -3.69499111 -7.09885406
 -1.5437305  -2.96987367 -1.66402376 -5.51040745 -4.49072266]
[  9.95230615e-01   2.83702072e-02   6.69852853e-01   1.00393230e-02
   2.42452361e-02   8.25369207e-04   1.75993621e-01   4.88055870e-02
   1.59222588e-01   4.02816758e-03   1.10882111e-02]
[1 0 1 0 0 0 0 0 0 0 0]
if not then #teamchristine bc all tana has done is provoke her by tweeting shady shit and trying to be a har

Time to #impeachtrump . He is #crazy #mentally #sick and spews #hatred . #America is in trouble with him having #access to #nuclearcodes 👎👎
['time', 'to', '<hashtag>', 'impeach', 'trump', '</hashtag>', '.', 'he', 'is', '<hashtag>', 'crazy', '</hashtag>', '<hashtag>', 'mentally', '</hashtag>', '<hashtag>', 'sick', '</hashtag>', 'and', 'spews', '<hashtag>', 'hatred', '</hashtag>', '.', '<hashtag>', 'america', '</hashtag>', 'is', 'in', 'trouble', 'with', 'him', 'having', '<hashtag>', 'access', '</hashtag>', 'to', '<hashtag>', 'nuclear', 'codes', '</hashtag>', '👎', '👎']
tensor([0.0232, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233,
        0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233,
        0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233,
        0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233,
        0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233, 0.0233],
       device='cuda:0', grad_fn=<DivBackwa

tensor([0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714,
        0.0714, 0.0714, 0.0714, 0.0714, 0.0714],
       device='cuda:0', grad_fn=<DivBackward1>)
[-1.55473423 -5.10378313 -1.02772295 -4.02210665 -4.87402153 -6.01801348
 -4.51133156  0.61613381  6.9780736  -5.20080948 -8.45963669]
[  1.74403548e-01   6.03705784e-03   2.63525784e-01   1.75998788e-02
   7.58460304e-03   2.42858846e-03   1.08644906e-02   6.49338722e-01
   9.99068797e-01   5.48188388e-03   2.11804145e-04]
[0 0 0 0 0 0 0 1 1 0 0]
@theIeansquad @SatanHeavenly Rap is so unbearable and horrific.
['<user>', '<user>', 'rap', 'is', 'so', 'unbearable', 'and', 'horrific', '.']
tensor([0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
       device='cuda:0', grad_fn=<DivBackward1>)
[  3.07567644  -5.29828024   3.33525348   0.6329574   -4.79601526
  -8.73671818  -6.57014656  -3.48405051   0.31553778  -5.44050169
 -10.12337589]
[  9.55878139e-01   4.97530820e-03   9.65618610e-01   6

@1720maryknoll I was #fuming Kenny.
['<user>', 'i', 'was', '<hashtag>', 'fuming', '</hashtag>', 'kenny', '.']
tensor([0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250],
       device='cuda:0', grad_fn=<DivBackward1>)
[ 6.81591654 -5.51835108  1.01680493 -6.84631062 -3.14197516 -8.37659931
 -4.79171848 -4.94006443 -1.51916957 -5.55741072 -8.51368999]
[  9.98905063e-01   3.99642298e-03   7.34349787e-01   1.06224208e-03
   4.14086469e-02   2.30138452e-04   8.22989177e-03   7.10331928e-03
   1.79583833e-01   3.84392240e-03   2.00661598e-04]
[1 0 1 0 0 0 0 0 0 0 0]
I've got builders in my office and I have a game to make. Perhaps ill start sketching the next game... #gamedev #indiedev 
['i', 'have', 'got', 'builders', 'in', 'my', 'office', 'and', 'i', 'have', 'a', 'game', 'to', 'make', '.', 'perhaps', 'ill', 'start', 'sketching', 'the', 'next', 'game', '.', '<repeated>', '<hashtag>', 'game', 'dev', '</hashtag>', '<hashtag>', 'indie', 'dev', '</hashtag>']
tensor([0.0312, 0.0312

Don't fucking tag me in pictures as 'family first' when you cut me out 5 years ago. You're no one to me. 
['do', 'not', 'fucking', 'tag', 'me', 'in', 'pictures', 'as', "'", 'family', 'first', "'", 'when', 'you', 'cut', 'me', 'out', '<number>', 'years', 'ago', '.', 'you', 'are', 'no', 'one', 'to', 'me', '.']
tensor([0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357,
        0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357,
        0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357, 0.0357,
        0.0357], device='cuda:0', grad_fn=<DivBackward1>)
[ 4.60967684 -4.19716597  3.54804707 -4.52396917 -4.02709198 -6.84164286
 -5.03904247 -2.86772084 -0.99202067 -4.66673088 -7.58894968]
[  9.90143061e-01   1.48153407e-02   9.72024322e-01   1.07295178e-02
   1.75138880e-02   1.06720661e-03   6.43823063e-03   5.37724979e-02
   2.70513147e-01   9.31536686e-03   5.05756354e-04]
[1 0 1 0 0 0 0 0 0 0 0]
Kid at camp said my inner thigh looked like

At this point I can't tell if I just follow more people in politics on twitter now or if I need new friends. #wheresthefunny #depressing
['at', 'this', 'point', 'i', 'can', 'not', 'tell', 'if', 'i', 'just', 'follow', 'more', 'people', 'in', 'politics', 'on', 'twitter', 'now', 'or', 'if', 'i', 'need', 'new', 'friends', '.', '<hashtag>', 'wheres', 'the', 'funny', '</hashtag>', '<hashtag>', 'depressing', '</hashtag>']
tensor([0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303,
        0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303,
        0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303,
        0.0303, 0.0303, 0.0303, 0.0303, 0.0303, 0.0303],
       device='cuda:0', grad_fn=<DivBackward1>)
[-2.45971727 -4.77745771 -0.0103243  -3.88765383 -5.69998789 -7.55421257
 -6.01724529  1.09971416  6.15648127 -4.15570211 -8.58103848]
[  7.87308440e-02   8.34710989e-03   4.97418910e-01   2.00818256e-02
   3.33484774e-03   5.23624185e-

@Amber02150 Good morning! Happy winter day. :)
['<user>', 'good', 'morning', '!', 'happy', 'winter', 'day', '.', '<happy>']
tensor([0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
       device='cuda:0', grad_fn=<DivBackward1>)
[-7.07868338 -4.22337484 -6.95672894 -7.91856337  6.77034903  0.32932091
  1.16628718 -8.42003918 -6.26357126 -4.09619951 -2.13519883]
[  8.42172361e-04   1.44376243e-02   9.51300433e-04   3.63792380e-04
   9.98854041e-01   5.81594169e-01   7.62473285e-01   2.20357455e-04
   1.90081249e-03   1.63635593e-02   1.05722465e-01]
[0 0 0 0 1 1 1 0 0 0 0]
@AmyJoSmyth #OOC Thing is she holds a grudge like mad
['<user>', '<hashtag>', 'ooc', '</hashtag>', 'thing', 'is', 'she', 'holds', 'a', 'grudge', 'like', 'mad']
tensor([0.0135, 0.0135, 0.0743, 0.0999, 0.0999, 0.0999, 0.0999, 0.0999, 0.0999,
        0.0999, 0.0999, 0.0999], device='cuda:0', grad_fn=<DivBackward1>)
[ 4.09132051 -4.52247858  0.60133594 -6.01873636 -3.83128643 -8.10108757
 -3.995226

@izzyaline burning up damn
['<user>', 'burning', 'up', 'damn']
tensor([0.2500, 0.2500, 0.2500, 0.2500], device='cuda:0', grad_fn=<DivBackward1>)
[ 1.93166006 -3.86928344  1.27804828 -2.13981843 -2.50724626 -6.73681355
 -4.01399803 -2.94329476 -0.44001848 -5.36740828 -7.01595354]
[ 0.87343305  0.02044654  0.78211743  0.10528649  0.07535174  0.00118502
  0.01774063  0.05005438  0.3917366   0.00464454  0.00089664]
[1 0 1 0 0 0 0 0 0 0 0]
#depressed Today was bitter sweet watching all the kids go back to school made me really miss my babies. I'm so broke #backtoschool2017
['<hashtag>', 'depressed', '</hashtag>', 'today', 'was', 'bitter', 'sweet', 'watching', 'all', 'the', 'kids', 'go', 'back', 'to', 'school', 'made', 'me', 'really', 'miss', 'my', 'babies', '.', 'i', 'am', 'so', 'broke', '<hashtag>', 'back', 'to', 'school', '2017', '</hashtag>']
tensor([0.0312, 0.0312, 0.0312, 0.0312, 0.0312, 0.0312, 0.0312, 0.0312, 0.0312,
        0.0312, 0.0312, 0.0312, 0.0312, 0.0312, 0.0312, 0.0312, 0.0

#Look at #those who are #honest and #good, for a #wonderful #future #awaits those who #love #peace.
['<hashtag>', 'look', '</hashtag>', 'at', '<hashtag>', 'those', '</hashtag>', 'who', 'are', '<hashtag>', 'honest', '</hashtag>', 'and', '<hashtag>', 'good', '</hashtag>', ',', 'for', 'a', '<hashtag>', 'wonderful', '</hashtag>', '<hashtag>', 'future', '</hashtag>', '<hashtag>', 'awaits', '</hashtag>', 'those', 'who', '<hashtag>', 'love', '</hashtag>', '<hashtag>', 'peace', '</hashtag>', '.']
tensor([0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270,
        0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270,
        0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270,
        0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270, 0.0270,
        0.0270], device='cuda:0', grad_fn=<DivBackward1>)
[-7.39491796 -3.59659576 -8.03908634 -7.5146122   5.68617296  1.0660336
  4.05675697 -9.47811699 -7.41398621 -5.04702568 -1.4296

@angrydwarf9 @carolinesandall It ruins my frigging night each night at 9pm. Mrs loves it, i've been early to bed for a month. #dreadful
['<user>', '<user>', 'it', 'ruins', 'my', 'frigging', 'night', 'each', 'night', 'at', '<time>', '.', 'mrs', 'loves', 'it', ',', 'i', 'have', 'been', 'early', 'to', 'bed', 'for', 'a', 'month', '.', '<hashtag>', 'dreadful', '</hashtag>']
tensor([0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345,
        0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345,
        0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345,
        0.0345, 0.0345], device='cuda:0', grad_fn=<DivBackward1>)
[  3.85715628  -5.34229517   3.90359616  -2.21251845  -4.11166716
  -8.29266167  -6.36526871  -2.73344159   0.02271445  -5.31217146
 -10.30404377]
[  9.79309201e-01   4.76208981e-03   9.80229497e-01   9.86319482e-02
   1.61164496e-02   2.50284589e-04   1.71732483e-03   6.10286444e-02
   5.05678356e-01   4.90700966e-03   

Like I might've set it down on top of my car &amp; if so, that shit is long gone 😭 
['like', 'i', 'might', "'", 've', 'set', 'it', 'down', 'on', 'top', 'of', 'my', 'car', '&', 'if', 'so', ',', 'that', 'shit', 'is', 'long', 'gone', '😭']
tensor([0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435,
        0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435, 0.0435,
        0.0435, 0.0435, 0.0435, 0.0435, 0.0435],
       device='cuda:0', grad_fn=<DivBackward1>)
[ 2.60772085 -3.89366865  1.59371686 -2.80701303 -3.3327632  -6.07936382
 -4.65581465 -1.68338943  0.95845789 -3.85193324 -7.37860823]
[  9.31356847e-01   1.99638046e-02   8.31138372e-01   5.69463782e-02
   3.44641618e-02   2.28440249e-03   9.41664912e-03   1.56647176e-01
   7.22812951e-01   2.07969397e-02   6.24079665e-04]
[1 0 1 0 0 0 0 0 1 0 0]
And I'm really pissed the fuck off because I do a good job of keeping my kid well because I don't like to see her sick and sad.
['and', 'i', 'am', 'really', 

@DirtyDucko @funder I wish I could like this twice. #hilarious
['<user>', '<user>', 'i', 'wish', 'i', 'could', 'like', 'this', 'twice', '.', '<hashtag>', 'hilarious', '</hashtag>']
tensor([0.0769, 0.0769, 0.0769, 0.0769, 0.0769, 0.0769, 0.0769, 0.0769, 0.0769,
        0.0769, 0.0769, 0.0769, 0.0769],
       device='cuda:0', grad_fn=<DivBackward1>)
[-5.46486044 -4.34466839 -5.10862303 -7.26142263  6.79909849 -0.9366188
  0.65635574 -7.60896301 -4.52438974 -1.28966212 -2.89561939]
[  4.21508960e-03   1.28095960e-02   6.00808533e-03   7.01615878e-04
   9.98886526e-01   2.81583816e-01   6.58441305e-01   4.95740038e-04
   1.07250549e-02   2.15910003e-01   5.23705371e-02]
[0 0 0 0 1 0 1 0 0 0 0]
Enter this code for 10 free Lyfts PARX #Isn't it great to save money when you shop? #blissful #FREECAB
['enter', 'this', 'code', 'for', '<number>', 'free', 'lyfts', '<allcaps>', 'parx', '</allcaps>', '<hashtag>', 'isn', '</hashtag>', "'", 't', 'it', 'great', 'to', 'save', 'money', 'when', 'you', 'sho

Sorry if I annoy any of you. I'm just real passionate about Ruby and always want to give her the love she deserves 😭
['sorry', 'if', 'i', 'annoy', 'any', 'of', 'you', '.', 'i', 'am', 'just', 'real', 'passionate', 'about', 'ruby', 'and', 'always', 'want', 'to', 'give', 'her', 'the', 'love', 'she', 'deserves', '😭']
tensor([0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385,
        0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385,
        0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385],
       device='cuda:0', grad_fn=<DivBackward1>)
[ 0.58643305 -3.6952703  -0.27695462 -4.31612349 -0.37144312  0.39069349
 -0.99424499 -2.15669131  0.08311769 -5.3344903  -3.85087347]
[ 0.6425463   0.02423863  0.43120053  0.01317563  0.40819237  0.59644961
  0.27007443  0.1037076   0.52076751  0.00479922  0.02081853]
[1 0 0 0 0 1 0 0 1 0 0]
if you wake up somewhere else...you will know some #arsehole has pressed a button ;)
['if', 'you', 'wake', 'up

Repeated terror attacks,no1 can define the religion of terrorists.\n1 guy arrested,Terrorists/ism got it's religion.
['repeated', 'terror', 'attacks', ',', 'no1', 'can', 'define', 'the', 'religion', 'of', 'terrorists', '.', '\\', 'n1', 'guy', 'arrested', ',', 'terrorists', '/', 'ism', 'got', 'it', "'", 's', 'religion', '.']
tensor([0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385,
        0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385,
        0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385, 0.0385],
       device='cuda:0', grad_fn=<DivBackward1>)
[ 1.32040536 -3.87695098  1.14033222  4.3412509  -5.01674509 -7.92796993
 -3.98728371 -2.49080229 -2.54728556 -6.28221893 -6.00765181]
[  7.89249122e-01   2.02935282e-02   7.57740676e-01   9.87147093e-01
   6.58244314e-03   3.60387639e-04   1.82121955e-02   7.65054971e-02
   7.26090595e-02   1.86576066e-03   2.45382171e-03]
[1 0 1 1 0 0 0 0 0 0 0]
@actor_nithiin Happy birthday Manisharma si

+ cant get to tell them what will offend them or not
['+', 'cant', 'get', 'to', 'tell', 'them', 'what', 'will', 'offend', 'them', 'or', 'not']
tensor([0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833,
        0.0833, 0.0833, 0.0833], device='cuda:0', grad_fn=<DivBackward1>)
[ 1.74839294 -1.63013113  1.77538443 -2.70592046 -3.65977812 -6.55398941
 -2.38362479 -1.57551968 -0.51438361 -3.00276804 -4.35873985]
[ 0.85175002  0.1638124   0.85512596  0.0626249   0.02509239  0.0014224
  0.08442994  0.17143093  0.37416646  0.04730098  0.01263287]
[1 0 1 0 0 0 0 0 0 0 0]
A trip to the dentist never gets any easier!! #nervous
['a', 'trip', 'to', 'the', 'dentist', 'never', 'gets', 'any', 'easier', '!', '<repeated>', '<hashtag>', 'nervous', '</hashtag>']
tensor([0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714, 0.0714,
        0.0714, 0.0714, 0.0714, 0.0714, 0.0714],
       device='cuda:0', grad_fn=<DivBackward1>)
[-4.99224424 -1.86754286 -3.98271084  7.48628759 

@0510Keisuke devour the unborn\nhuman rejection\nfrom wrath to ruins
['<user>', 'devour', 'the', 'unborn', '\\', 'nhuman', 'rejection', '\\', 'nfrom', 'wrath', 'to', 'ruins']
tensor([0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833, 0.0833,
        0.0833, 0.0833, 0.0833], device='cuda:0', grad_fn=<DivBackward1>)
[ 1.60728741 -3.73549533  1.59067976 -2.07552528 -5.81047678 -8.95082951
 -4.46336555 -2.29794669 -0.85282177 -7.44650316 -7.69842005]
[  8.33034456e-01   2.33052541e-02   8.30711663e-01   1.11498497e-01
   2.98705208e-03   1.29612788e-04   1.13922367e-02   9.12931636e-02
   2.98841268e-01   5.83138084e-04   4.53337590e-04]
[1 0 1 0 0 0 0 0 0 0 0]
Each of us have varied #talents #gifts &amp; #abilities If we #all #work #together #we can #help #make the #world a #better &amp; #brighter #place
['each', 'of', 'us', 'have', 'varied', '<hashtag>', 'talents', '</hashtag>', '<hashtag>', 'gifts', '</hashtag>', '&', '<hashtag>', 'abilities', '</hashtag>', 'if', 'we', '<ha

#CNN really needs to get out of the #Propaganda Business.. 30 seconds on USN fallen Soldiers tragedy. Right back at spewing #hatred #POTUS
['<hashtag>', 'cnn', '</hashtag>', 'really', 'needs', 'to', 'get', 'out', 'of', 'the', '<hashtag>', 'propaganda', '</hashtag>', 'business', '.', '<repeated>', '<number>', 'seconds', 'on', '<allcaps>', 'usn', '</allcaps>', 'fallen', 'soldiers', 'tragedy', '.', 'right', 'back', 'at', 'spewing', '<hashtag>', 'hatred', '</hashtag>', '<hashtag>', 'potus', '</hashtag>']
tensor([0.0041, 0.0041, 0.0041, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299,
        0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299,
        0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299,
        0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299, 0.0299],
       device='cuda:0', grad_fn=<DivBackward1>)
[  5.75143194  -4.66445589   4.66560316  -5.82245302  -5.61492729
  -9.86143875  -6.21788216  -2.79893088  -0.08276093  -6.37

tensor([0.0098, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354,
        0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354,
        0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354, 0.0354,
        0.0354, 0.0354], device='cuda:0', grad_fn=<DivBackward1>)
[ 2.961658   -3.7570343   2.73040891 -3.63784528  0.27583912 -5.12031841
 -2.53359866 -3.38297701 -2.09199739 -3.79381323 -5.99638605]
[ 0.95081162  0.02281998  0.93879735  0.02563455  0.56852585  0.00593864
  0.0735361   0.03283173  0.10987707  0.02201407  0.00248155]
[1 0 1 0 1 0 0 0 0 0 0]
I've never been so excited to start a semester!
['i', 'have', 'never', 'been', 'so', 'excited', 'to', 'start', 'a', 'semester', '!']
tensor([0.0909, 0.0909, 0.0909, 0.0909, 0.0909, 0.0909, 0.0909, 0.0909, 0.0909,
        0.0909, 0.0909], device='cuda:0', grad_fn=<DivBackward1>)
[-5.06694555  0.90189379 -5.82690668 -0.54998863  2.90805626 -2.28185582
  0.63985127 -4.8374505  -5.41293907 -2.07762885

252

In [23]:
cnt # acc >= 0.9; 0.5 245, 0.3 191 => first model, # new model 252

191

In [20]:
# 448 <= 0.5

In [25]:
a = {1:[]}

In [26]:
a = set()
a.add(1)
a.add(1)
a

{1}